### ISSUE TITLE
Universal Transformer for Translation

### ISSUE THREAD

**Issue by RayWangWR** [konstantinosKokos/UniversalTransformer#2]
Hi

Thank you very much for your excellent code base. I want to know if the universal transformer tested on any translation task, e.g. En->De, and how does it look like? If convenient, could you please share the parameter configuration or the code for translation?

Regards,
Rui

**Comment by konstantinosKokos** [comment]
Yo Rui

I have only toyed around with some computational tasks (sequence segmentation) and hierarchical parsing with the UT. I have found that generally it is both slower and lesser performing to the standard Transformer, which is also what the absence of follow-up papers in the literature suggests. Note that the dynamic timer is not implemented either. 

Sorry to disappoint and thanks for your interest :) 
Kokos
